### ISSUE TITLE
Support defining a name for imported operations

### ISSUE THREAD

**Issue by markallanson** [event-catalog/generator-openapi#40]
### Use Case

At the moment the unique identifier for an operation is used as the message ID and Name.

It would be nice to be able to supply an event catalog specific friendly name for the operation

### Proposed Solution

Support parsing an `x-eventcatalog-operation-name` type field in the operation that can be used to set the name in the event catalog.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Yeah I like the idea, maybe we can have two?

EventCatalog has `id` and `name`, id tends to be used for the slug and name used for the friendly name.

I think having `x-eventcatalog-message-name` and `x-eventcatalog-message-id`could work?

**Comment by markallanson** [comment]
This would work so long as it defaults to using the name of the operation in the open API file and only use the override if it's present?

**Comment by boyney123** [comment]
Yeah, keep it as it is, and only use the id/name if you specify them. Optional feature, defaults to how it works today. Does that work?

**Comment by markallanson** [comment]
It does for me.

**Comment by boyney123** [comment]
Released in 3.0.0

https://www.eventcatalog.dev/docs/development/plugins/open-api/features#define-eventcatalog-ids-and-names-in-your-openapi-specification-file

Thanks for raising the idea!
