### ISSUE TITLE
Make operation description available within the generated message

### ISSUE THREAD

**Issue by markallanson** [event-catalog/generator-openapi#41]
### Use Case

Operations allow you to specify a summary, and a longer form description. The current plugin uses the description as the message summary when the operation has no summary.

When the operation has a summary the description is not shown anywhere.

### Proposed Solution

Add the operation description to the markdown content of the message _before_ the schema is rendered. 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Thanks for raising this issue @markallanson .

This is now fixed in `2.3.2`.
